### ISSUE TITLE
Memory leak in coupled replay run

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/GEOSgcm#244] opened 2021-01-07 20:17 UTC
When running a coupled model in replay mode with dual ocean set up, memory usage is growing until the model crashes with "insufficient virtual memory" error. Example printout:
```
AGCM Date: 1980/01/01  Time: 03:07:30  Throughput(days/day)[Avg Tot Run]:   15.2   15.2   17.8  TimeRemaining(Est) 049:02:35   31.8% :  20.5% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  3.449E+04  0.000E+00
...
AGCM Date: 1980/01/03  Time: 10:45:00  Throughput(days/day)[Avg Tot Run]:  302.3  450.0  457.1  TimeRemaining(Est) 002:16:37   52.0% :  39.4% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  5.932E+04  0.000E+00
```

Free coupled run does not have this problem. If I switch dual ocean mode off, but leave the replay on, memory also leaks (ocean IC do not cycle correctly in this case, this experiment just shows what happens when the code inside if(dual_ocean == true) is bypassed).

**Comment by atrayano** [comment] 2021-01-07 20:40
@yvikhlya Replay needs to save all the "checkpoints" in memory before we start the predictor step. Once this is done, we rewind the clock and read back these "saved" checkpoint. At this point these buffers should be freed, otherwise we could have a big memory leak. If I remember correctly, there was a similar bug in the past, but it was fixed. I will double check this though. Other than that, replay should not be very different from a "normal" free run. We also call mkIAU, and we should check it for leaks too.

**Comment by bena-nasa** [comment] 2021-01-08 21:14
The culprit appears not to be the dual ocean, rather the experiment that led to this discover had this set in the resource file:
```
PRECIP_FILE: ExtData/PCP/d5_merra/Y%y4/M%m2/d5_merra.tavg1_2d_lfo_Nx_corr.%y4%m2%d2_%h230z.nc
```
This causes both the Surface and ChemEnv gridded components to read several variables from the file using MAPL_CFIORead every timestep. This read is the cause of the memory leak.

**Comment by yvikhlya** [comment] 2021-01-08 21:57
This is a precipitation correction code and it is working fine in S2Sv3 tag. What changed in jason?

**Comment by bena-nasa** [comment] 2021-01-08 22:10
Nothing with this code as far as I'm aware, my current theory is that each time this read a fresh bundle is created and this includes allocating fields that are never destroyed. I'm trying now to properly create them so ESMF can actually deallocate them without having to retrieve the pointer. Although why this was not seen in earlier versions is a mystery.

**Comment by sanAkel** [comment] 2021-01-13 18:37
@bena-nasa does it imply that if there was no `precipitation correction` there would be no problem: no memory leak?

**Comment by mathomp4** [comment] 2021-01-14 13:05
I want to say that @bena-nasa saw no memory leak if the file wasn't read, but he can answer more accurately. I know he got to a point where the memory leak was gone.

**Comment by sanAkel** [comment] 2021-01-27 13:19
> The culprit appears not to be the dual ocean, rather the experiment that led to this discover had this set in the resource file:
> 
> ```
> PRECIP_FILE: ExtData/PCP/d5_merra/Y%y4/M%m2/d5_merra.tavg1_2d_lfo_Nx_corr.%y4%m2%d2_%h230z.nc
> ```
> 
> This causes both the Surface and ChemEnv gridded components to read several variables from the file using MAPL_CFIORead every timestep. This read is the cause of the memory leak.

@bena-nasa or @yvikhlya or someone else, which gridded component is actually **applying** this precipitation _correction_? I understand from above @bena-nasa's comment that it is being **read** by 
>Surface and ChemEnv gridded components

Ideally please point me to the **exact** lines of code. I would appreciate that. Thanks!

**Comment by mathomp4** [comment] 2021-01-27 13:58
Well, in Chem it seems to be this chunk:
https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/6c086cadcdd418912ddff392f46ec4039bf7fcc3/GEOS_ChemEnvGridComp.F90#L458-L507
and in Surf it looks like this chunk:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/e0cf9fabbe700c3e23571466f444973dd6b20e4e/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90#L5748-L5834

**Comment by bena-nasa** [comment] 2021-02-12 21:18
The final issue was that  MAPL_CFIORead is using the "old" regridding layers in MAPL which apparently have a memory leak in my testing. I was unable to pinpoint exactly where but it was definitely the fact that it was making a regridder with the old (non-esmf) regridding layer. I delivered a temporary patch to Yuri to get him by that moves the regridding out of MAPL_CFIOread by reading passing a bundle with the same resolution as the file and regridding with ESMF outside the call. This is not ideal and I have  created a MAPL_CFIO replacement layer that hopefully will be in MAPL's develop branch soon.

**Comment by sanAkel** [comment] 2021-03-22 18:44
All ⤴️ seem resolved. Closing for now.

**Closed by sanAkel** 2021-03-22 18:44 UTC
Labels: bug
